dependency-dir: ./src

depends:
  - test-runner

target.arm:
    - src/board.c
    - src/usbconf.c
    - src/cmd.c
    - src/mpu9250.c
    - src/main.c

source:
    - src/dw1000/dw1000.c

include_directories:
    - src/

tests:
    - tests/dw1000/test_driver.cpp
    - tests/dw1000/mocks.cpp

templates:
    app_src.mk.jinja: app_src.mk
